PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE COMPANY(
ID INT PRIMARY KEY NOT NULL,
NAME TEXT NOT NULL,
AGE INT NOT NULL,
ADDRESS CHAR(50),
SALARY REAL
);
INSERT INTO "COMPANY" VALUES(1,'Rohit',24,'Bangalore',20000.0);
INSERT INTO "COMPANY" VALUES(2,'Rahul',22,'Dharwad',25000.0);
CREATE TABLE DEPARTMENT(
ID INT PRIMARY KEY NOT NULL,
DEPT CHAR(50) NOT NULL,
EMP_ID INT NOT NULL
);
CREATE TABLE Cars(Id INT,Name TEXT,Price Int);
INSERT INTO "Cars" VALUES(1,'Honda',52642);
INSERT INTO "Cars" VALUES(2,'Mercedes',57127);
INSERT INTO "Cars" VALUES(3,'Skoda',9000);
INSERT INTO "Cars" VALUES(4,'Volvo',29000);
INSERT INTO "Cars" VALUES(5,'Bentley',350000);
INSERT INTO "Cars" VALUES(6,'Hummer',41400);
INSERT INTO "Cars" VALUES(7,'Volkswagen',21600);
COMMIT;
